// Tipos de ações
export const SUCESSO_REGISTRO = "SUCESSO_REGISTRO";
export const FALHA_REGISTRO = "FALHA_REGISTRO";
export const SUCESSO_LOGIN = "SUCESSO_LOGIN";
export const FALHA_LOGIN = "FALHA_LOGIN";
export const LOGOUT = "LOGOUT";
export const EMAIL_NAO_EXISTE = "EMAIL_NAO_EXISTE";

export const SETAR_MENSAGEM = "SETAR_MENSAGEM";
export const LIMPAR_MENSAGEM = "LIMPAR_MENSAGEM";

export const SENHA_RECUPERADA = "SENHA_RECUPERADA";

export const INSTALACAO_CADASTRADA = "INSTALACAO_CADASTRADA";
